apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  # property-like keys; each key maps to a simple value
  quarkus.datasource.jdbc.url: "jdbc:postgresql://postgres-container:5432/postgres"
  price.tax.boost: "true"
