apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pgdb-user
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","configmaps","secrets"]
  verbs: ["get", "watch", "list"]
