name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: 131Woody/CICD_Academy/.github/actions/docker_build@main
      with: 
        tag_name: v1
        image_name: car-app-list

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      uses: 131Woody/CICD_Academy/.github/actions/docker_push@main 
      with:
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        image_name: ${{ env.DOCKER_IMAGE_NAME }}
  