name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: 131Woody/CICD_Academy/.github/actions/docker_build@main
      with: 
        tag_name: v1
        image_name: car-app-list

  