name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    services:
      # Label used to access the service container
      postgres-container:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: 1234
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto' 
        java-version: '17'
    - uses: 131Woody/CICD_Academy/.github/actions/docker_build@main
      with: 
        tag_name: v1
        image_name: car-app-list

    - name: Run maven tests
      run: mvn test

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      uses: 131Woody/CICD_Academy/.github/actions/docker_push@main 
      with:
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        image_name: ${{ env.DOCKER_IMAGE_NAME }}
  